
resources:
  containers:
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04

jobs:
 - job: Linux
   pool:
     vmImage: 'Ubuntu 16.04'

   container: wpilib2019

   steps:
   - task: Gradle@2
     inputs:
       workingDirectory: ''
       gradleWrapperFile: 'gradlew'
       gradleOptions: '-Xmx3072m'
       publishJUnitResults: false
       tasks: 'build publish'

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: maven repo'
     inputs:
       PathtoPublish: 'build/publishing'
       ArtifactName: 'LinuxMaven'

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: Plugin'
     inputs:
       PathtoPublish: 'build/libs/*.jar'
       ArtifactName: 'Plugin'