
resources:
  containers:
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04

jobs:
 - job: Linux
   pool:
     vmImage: 'Ubuntu 16.04'

   container: wpilib2019

   steps:
   - task: Gradle@2
     inputs:
       workingDirectory: ''
       gradleWrapperFile: 'gradlew'
       gradleOptions: '-Xmx3072m'
       publishJUnitResults: false
       tasks: 'build publish'

   - task: ArchiveFiles@2
     displayName: 'Archive Maven Artifact'
     inputs:
       archiveFile: '$(Build.ArtifactStagingDirectory)/MavenRepo.zip' 
       rootFolderOrFile: build/publishing
       
   - task: CopyFiles@2
     inputs:
       sourceFolder: 'build/libs'
       contents: '*.jar'
       targetFolder: $(Build.ArtifactStagingDirectory)

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: Plugin'
     inputs:
       pathtoPublish: $(Build.ArtifactStagingDirectory)
       ArtifactName: 'artifacts'
       
   - script: |
      echo Write your commands here
      
      echo Use the environment variables input below to pass secret variables to this script
      
      dir
      dir $(Build.ArtifactStagingDirectory)
      dir "SourceAlias"
      dir "SourceAlias\LinuxMaven"
      dir "SourceAlias\Plugin"
      dir
   
  displayName: 'Command Line Script'
   #- task: GitHubRelease@0
   #  displayName: 'GitHub release (create)'
   #  inputs:
   #    gitHubConnection: 'GitHub connection 1'
   #    repositoryName: pjreiniger/XCatsDeepSpaceDashboard
   #    tagSource: manual
   #    tag: '$(myTagName)'
   #    assets: |
   #     $(System.DefaultWorkingDirectory)/Plugin/*.jar
   #     $(System.DefaultWorkingDirectory)/LinuxMaven/*.zip
   #     $(System.DefaultWorkingDirectory)/*.zip
   #     $(Build.ArtifactStagingDirectory)/*.zip
   #     
   #     $(System.DefaultWorkingDirectory)/SourceAlias/Plugin/*.jar
   #     $(System.DefaultWorkingDirectory)/SourceAlias/LinuxMaven/*.zip
        
       