
resources:
  containers:
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04

jobs:
 - job: Linux
   pool:
     vmImage: 'Ubuntu 16.04'

   container: wpilib2019

   steps:
   - task: Gradle@2
     inputs:
       workingDirectory: ''
       gradleWrapperFile: 'gradlew'
       gradleOptions: '-Xmx3072m'
       publishJUnitResults: false
       tasks: 'build publish'

   - task: ArchiveFiles@2
     displayName: 'Archive Maven Artifact'
     inputs:
       rootFolderOrFile: build/publishing

   - task: CopyFiles@2
     displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
     inputs:
       SourceFolder: 'build/libs'
       Contents: '**/*.jar'
       TargetFolder: '$(build.artifactstagingdirectory)'

   - task: PublishBuildArtifacts@1
     displayName: 'Publish Artifact: Plugin'
     inputs:
       PathtoPublish: '$(build.artifactstagingdirectory)'
       ArtifactName: 'Plugin'
